[package]
name = "fedra"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
ego-tree = "0.10.0"
reqwest = { version = "0.13.1", features = ["blocking", "form", "json", "multipart", "rustls"] }
scraper = "0.25.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tts = { version = "0.26.3", features = ["tolk"] }
tungstenite = { version = "0.28.0", features = ["native-tls"] }
url = "2.5.8"
wxdragon = { git = "https://github.com/AllenDang/wxDragon", branch = "main", version = "0.9.8" }

[build-dependencies]
embed-manifest = "1.5.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1
