[package]
name = "fedra"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
wxdragon = "0.9.7"

[build-dependencies]
embed-manifest = "1.5.0"
