[package]
name = "fedra"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13.1", features = ["blocking", "form", "json", "rustls"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
url = "2.5.8"
webbrowser = "1.0.6"
wxdragon = "0.9.7"

[build-dependencies]
embed-manifest = "1.5.0"
